-- =============================================================================
--  HERMOD, THE SPIRIT OF WAR  [v3.0]
--  MemoryError RS3 Client | Lua
--
--  SINGLE FILE — no external library dependencies.
--  Requires ONLY: api.lua and usertypes.lua (auto-generated by MemoryError)
--
--  PLACE THIS FILE IN: Lua_Scripts\
--  RUN AS: hermod_v3.0  (select it in MemoryError Script Manager)
--
--  CONFIGURE: edit the CONFIG section below before running.
-- =============================================================================

local API       = require("api")
local usertypes = require("usertypes")

print("[Hermod v3.0] Script loaded.")

-- =============================================================================
--  CONFIG — edit these before running
-- =============================================================================
local CONFIG = {
    -- HP management
    eatAtHpPct       = 50,    -- eat food when HP drops below this %
    emergencyHpPct   = 30,    -- eat emergency food below this %

    -- Prayer management
    restoreAtPrayPct = 20,    -- drink prayer restore below this %

    -- Loot window
    lootWindowSecs   = 12,    -- seconds to spend looting after each kill

    -- Loop timing
    loopSleepMs      = 150,
    loopSleepVar     = 50,
}

-- =============================================================================
--  NPC / ITEM IDs — verify in-game with MemoryError overlays
-- =============================================================================
local NPC_ID = {
    HERMOD           = 30163,
    ARMOURED_PHANTOM = 30164,
}

-- Item IDs to loot (add/remove as needed)
local LOOT_IDS = {
    49394,  -- Hermodic plate   (~1/10)
    49395,  -- Hermod's armour spike (1/2000) — verify this ID in-game
    995,    -- Coins
    536,    -- Big bones
}

-- =============================================================================
--  STATE MACHINE
-- =============================================================================
local States = {
    WAITING         = "WAITING FOR HERMOD",
    FIGHTING_BOSS   = "FIGHTING BOSS",
    KILLING_MINIONS = "KILLING MINIONS",
    LOOTING         = "LOOTING",
}

local state         = States.WAITING
local killCount     = 0
local sessionStart  = os.time()
local lootStartTime = 0
local lastAttackMs  = 0
local lastLootMs    = 0

-- =============================================================================
--  HELPERS
-- =============================================================================
local function getNPCs(id, range)
    return API.GetAllObjArrayInteract({id}, 1, range or 30) or {}
end

local function hermodExists()  return #getNPCs(NPC_ID.HERMOD,           30) > 0 end
local function getPhantoms()   return getNPCs(NPC_ID.ARMOURED_PHANTOM,  30)     end
local function phantomsAlive() return #getPhantoms() > 0                        end

local function attackNPC(id)
    return API.DoAction_NPC1(0x10, API.OFF_ACT_NpcT_route, {id}, 30)
end

local function nowMs()
    return os.clock() * 1000
end

local function attackWithCooldown(npcId, cooldownMs)
    local t = nowMs()
    if t - lastAttackMs >= cooldownMs then
        lastAttackMs = t
        attackNPC(npcId)
    end
end

local function lootItems()
    local t = nowMs()
    if t - lastLootMs < 700 then return end
    lastLootMs = t
    for _, itemId in ipairs(LOOT_IDS) do
        local ground = API.GetAllObjArrayInteract({itemId}, 4, 8)
        if ground and #ground > 0 then
            print(string.format("[Hermod] Looting item %d", itemId))
            API.DoAction_Object1(0x5, API.OFF_ACT_GeneralObject_route0, {itemId}, 8)
            API.RandomSleep2(350, 60, 60)
        end
    end
end

local function manageHp()
    local hp = API.GetHP and API.GetHP() or 100
    if hp <= CONFIG.emergencyHpPct then
        -- Use emergency food (slot varies — Revolution or action bar slot 1)
        API.DoAction_Inventory1({29448}, 0, 1, API.OFF_ACT_GeneralInterface_route)
    elseif hp <= CONFIG.eatAtHpPct then
        -- Use normal food
        API.DoAction_Inventory1({47531}, 0, 1, API.OFF_ACT_GeneralInterface_route)
    end
end

local function managePrayer()
    local pp = API.GetPrayPrecent and API.GetPrayPrecent() or 100
    if pp <= CONFIG.restoreAtPrayPct then
        -- Super restore flask — adjust item ID if using different potion
        API.DoAction_Inventory1({23741}, 0, 1, API.OFF_ACT_GeneralInterface_route)
    end
end

-- =============================================================================
--  STATE TRANSITIONS
-- =============================================================================
local function updateState()
    local hermodPresent  = hermodExists()
    local minionsPresent = phantomsAlive()

    if state == States.WAITING then
        if hermodPresent then
            print("[Hermod] Hermod detected — starting fight!")
            state = States.FIGHTING_BOSS
        end

    elseif state == States.FIGHTING_BOSS then
        if not hermodPresent then
            killCount     = killCount + 1
            lootStartTime = os.time()
            print(string.format("[Hermod] Kill #%d! Looting...", killCount))
            state = States.LOOTING
        elseif minionsPresent then
            print(string.format("[Hermod] %d phantoms spawned — switching target!", #getPhantoms()))
            state = States.KILLING_MINIONS
        end

    elseif state == States.KILLING_MINIONS then
        if not minionsPresent then
            if hermodPresent then
                print("[Hermod] Phantoms dead — back to Hermod!")
                state = States.FIGHTING_BOSS
            else
                killCount     = killCount + 1
                lootStartTime = os.time()
                print(string.format("[Hermod] Kill #%d! Looting...", killCount))
                state = States.LOOTING
            end
        end

    elseif state == States.LOOTING then
        if os.time() - lootStartTime >= CONFIG.lootWindowSecs then
            lootStartTime = 0
            print("[Hermod] Loot window done — waiting for next spawn.")
            state = States.WAITING
        end
    end
end

-- =============================================================================
--  STATUS DISPLAY
-- =============================================================================
local function displayStatus()
    local t   = os.time() - sessionStart
    local rt  = string.format("%02d:%02d:%02d",
        math.floor(t/3600), math.floor((t%3600)/60), t%60)
    local kph = t > 60 and string.format("%.1f/hr", killCount / (t/3600)) or "—"
    local hp  = (API.GetHP and API.GetHP()) or 0
    local pp  = (API.GetPrayPrecent and API.GetPrayPrecent()) or 0

    API.DrawTable({
        { "Hermod v3.0",    ""                                             },
        { "State",          state                                          },
        { "─────────",      "─────────"                                   },
        { "Kills",          tostring(killCount) .. "  (" .. kph .. ")"    },
        { "Runtime",        rt                                             },
        { "─────────",      "─────────"                                   },
        { "HP",             string.format("%d%%", hp)                     },
        { "Prayer",         string.format("%d%%", pp)                     },
        { "─────────",      "─────────"                                   },
        { "Hermod alive",   tostring(hermodExists())                      },
        { "Phantoms alive", tostring(#getPhantoms())                      },
    })
end

-- =============================================================================
--  MAIN LOOP
-- =============================================================================
print("[Hermod v3.0] Starting. Stand inside Hermod's instance.")
print(string.format("[Hermod v3.0] Eat at %d%% HP | Prayer restore at %d%%",
    CONFIG.eatAtHpPct, CONFIG.restoreAtPrayPct))

while API.Read_LoopyLoop() do

    -- 1. Manage HP and prayer every tick
    manageHp()
    managePrayer()

    -- 2. State transitions
    updateState()

    -- 3. Combat actions
    if state == States.FIGHTING_BOSS then
        attackWithCooldown(NPC_ID.HERMOD, 1800)

    elseif state == States.KILLING_MINIONS then
        attackWithCooldown(NPC_ID.ARMOURED_PHANTOM, 1200)

    elseif state == States.LOOTING then
        lootItems()
    end

    -- 4. Status overlay
    displayStatus()

    -- 5. Sleep
    API.RandomSleep2(CONFIG.loopSleepMs, CONFIG.loopSleepVar, CONFIG.loopSleepVar)
end

print(string.format("[Hermod v3.0] Stopped. Kills: %d | Runtime: %ds",
    killCount, os.time() - sessionStart))
